// apps/web/app/builder/page.tsx
"use client"
import { AiPromptBar } from '@/components/builder/AiPromptBar'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { useAiBuilder } from '@/hooks/useAiBuilder'

const templates = [
  { name: 'Kasir POS', prompt: 'buatkan aplikasi kasir', icon: '🛒' },
  { name: 'CRM Klinik', prompt: 'buatkan CRM untuk klinik', icon: '🏥' },
  { name: 'Todo Share', prompt: 'todo app dengan fitur share', icon: '✅' }
]

export default function BuilderPage() {
  const router = useRouter()
  const { generate } = useAiBuilder()

  async function onGenerate(prompt: string) {
    try {
      const res: any = await generate(prompt)
      toast.success(res.message || 'Generate dimulai')
      setTimeout(() => router.push(res.previewUrl || `/builder/${res.project.slug}`), 600)
    } catch (e: any) {
      toast.error(e.message || 'Gagal generate')
    }
  }

  return (
    <div className="min-h-screen bg-[#f6f5f4] p-8">
      <div className="max-w-[960px] mx-auto">
        <AiPromptBar onGenerate={onGenerate} />
        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4 max-w-[720px] mx-auto">
          {templates.map(t => (
            <div
              key={t.name}
              onClick={() => onGenerate(t.prompt)}
              className="bg-card rounded-xl border p-4 hover:shadow-md cursor-pointer transition"
            >
              <div className="text-xl">{t.icon}</div>
              <div className="font-semibold mt-2">{t.name}</div>
              <div className="text-sm text-muted-foreground mt-1">{t.prompt}</div>
              <div className="text-xs font-semibold tracking-wide uppercase text-primary mt-3">Gunakan Template →</div>
            </div>
          ))}
        </div>
        <div className="mt-8 max-w-[720px] mx-auto">
          <h3 className="font-semibold">Library</h3>
          <p className="text-sm text-muted-foreground">Project yang sudah di-generate akan muncul di sini. Endpoint: <code>GET /api/builder/projects</code></p>
        </div>
      </div>
    </div>
  )
}

// apps/web/app/pages/builder/index.vue
<script setup lang="ts">
import AiPromptBar from '~/components/builder/AiPromptBar.vue'
import { useMessage } from 'naive-ui'

definePageMeta({ middleware: 'auth' })

const message = useMessage()
const router = useRouter()
const aiBuilder = useAiBuilder()

async function onGenerate(prompt: string) {
  try {
    const res: any = await aiBuilder.generate(prompt)
    message.success(res.message || 'Generate dimulai — preparing preview...')
    // In full implementation: poll generation status then redirect to /builder/${slug} or /generated/${slug}
    setTimeout(() => router.push(res.previewUrl || `/builder/${res.project.slug}`), 800)
  } catch (e: any) {
    message.error(e?.data?.message || e?.message || 'Gagal generate')
  }
}
</script>

<template>
  <div class="min-h-screen bg-[#f6f5f4] p-8">
    <div class="max-w-[960px] mx-auto">
      <AiPromptBar @generate="onGenerate" />

      <!-- Template Gallery stub -->
      <div class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4 max-w-[720px] mx-auto">
        <div v-for="t in [
          { name: 'Kasir POS', prompt: 'buatkan aplikasi kasir', icon: '🛒' },
          { name: 'CRM Klinik', prompt: 'buatkan CRM untuk klinik', icon: '🏥' },
          { name: 'Todo Share', prompt: 'todo app dengan fitur share', icon: '✅' }
        ]" :key="t.name" class="bg-white rounded-[12px] border border-[#e6e6e6] p-4 hover:shadow-[0_4px_18px_rgba(0,0,0,0.04)] cursor-pointer transition" @click="onGenerate(t.prompt)">
          <div class="text-[20px]">{{ t.icon }}</div>
          <div class="font-semibold mt-2">{{ t.name }}</div>
          <div class="text-[13px] text-[#615d59] mt-1">{{ t.prompt }}</div>
          <div class="text-[11px] font-semibold tracking-[0.05em] uppercase text-[#0075de] mt-3">Gunakan Template →</div>
        </div>
      </div>

      <!-- Project Library placeholder -->
      <div class="mt-8 max-w-[720px] mx-auto">
        <h3 class="font-semibold text-[16px]">Library</h3>
        <p class="text-[13px] text-[#615d59]">
          Project yang sudah di-generate akan muncul di sini. Endpoint: <code>GET /api/builder/projects</code>
        </p>
      </div>
    </div>
  </div>
</template>
